// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChMZZo3wNLnfyVezudfTQr31PfrjaJ8jU',
    appId: '1:1076972330857:web:0f8e0aec42abbd3fcca7f8',
    messagingSenderId: '1076972330857',
    projectId: 'paulus-connect',
    authDomain: 'paulus-connect.firebaseapp.com',
    storageBucket: 'paulus-connect.firebasestorage.app',
    measurementId: 'G-RJZK9TYXFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLFALjeUs1MofzMZveMUjBIzMvc4ylHY',
    appId: '1:1076972330857:android:ae02756458995efacca7f8',
    messagingSenderId: '1076972330857',
    projectId: 'paulus-connect',
    storageBucket: 'paulus-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7MrhYKGIlhpCWjdwWmKtH189aBynVzZY',
    appId: '1:1076972330857:ios:ac766cd51b7ad8cdcca7f8',
    messagingSenderId: '1076972330857',
    projectId: 'paulus-connect',
    storageBucket: 'paulus-connect.firebasestorage.app',
    iosBundleId: 'com.example.paulus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7MrhYKGIlhpCWjdwWmKtH189aBynVzZY',
    appId: '1:1076972330857:ios:ac766cd51b7ad8cdcca7f8',
    messagingSenderId: '1076972330857',
    projectId: 'paulus-connect',
    storageBucket: 'paulus-connect.firebasestorage.app',
    iosBundleId: 'com.example.paulus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChMZZo3wNLnfyVezudfTQr31PfrjaJ8jU',
    appId: '1:1076972330857:web:a1062b22a63bb3b3cca7f8',
    messagingSenderId: '1076972330857',
    projectId: 'paulus-connect',
    authDomain: 'paulus-connect.firebaseapp.com',
    storageBucket: 'paulus-connect.firebasestorage.app',
    measurementId: 'G-W5ZSCT6KJD',
  );

}